---
Gemfile:
  optional:
    ':system_tests':
      - gem: 'voxpupuli-acceptance'
        version: '~> 3.1'
    ':test':
      - gem: 'redis'
      - gem: 'mock_redis'
spec/spec_helper.rb:
  mock_with: ":mocha"
